#!/usr/bin/env python
"""Regenerate ``docs/reference/cli.md`` from the Typer application.

Run ``uv run python scripts/gen_cli_reference.py``.  ``tests/test_docs.py`` fails when
the committed page differs from what this script renders, so the reference cannot drift
from the code.
"""

from __future__ import annotations

import sys
from pathlib import Path

import typer
from typer.cli import MARKUP_MODE_KEY, get_docs_for_click
from typer.main import get_command

from harnesslab.cli import app

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "reference" / "cli.md"
HEADER = (
    "<!-- Generated by scripts/gen_cli_reference.py from harnesslab.cli. Do not edit by hand;"
    " run `uv run python scripts/gen_cli_reference.py`. -->\n\n"
)
INTRO = (
    "Every command takes `--home <dir>` (or `HARNESSLAB_HOME`) to choose the data directory;"
    " the default is `./.harnesslab`. Run `harnesslab <command> --help` for the same text in"
    " the terminal.\n\n"
)


def render() -> str:
    command = get_command(app)
    ctx = typer.Context(command, info_name="harnesslab")
    ctx.obj = {MARKUP_MODE_KEY: app.rich_markup_mode}
    body = get_docs_for_click(obj=command, ctx=ctx, name="harnesslab", title="CLI reference")
    return HEADER + body.replace("# CLI reference\n\n", "# CLI reference\n\n" + INTRO, 1)


def main() -> int:
    text = render()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    if "--check" in sys.argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT} is stale; run this script without --check", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is current")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
